services:
  tbot_db:
    image: 'postgres:14'
    container_name: tbot_db
    environment:
      POSTGRES_DB: "tbot_test"
      POSTGRES_USER: "mawus"
      POSTGRES_PASSWORD: "mawus"
    ports:
      - '5432'
    networks:
      - tbot
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mawus -d tbot_test"]
      interval: 10s
      timeout: 5s
      retries: 5
# AFTER IMPLEMENT RMI
#  core:
#    build: ./modules/core
#    container_name: core-service
#    ports:
#      - "8081:8081"
#    depends_on:
#      "tbot_db":
#        condition: service_healthy
#    networks:
#      - tbot
  api:
    build: ./modules/api
    container_name: api-service
    ports:
      - "8080:8080"
    depends_on:
#      - core
      - tbot_db
    networks:
      - tbot
  bot:
    build: ./modules/bot
    container_name: bot-service
    ports:
      - "8082:8082"
    depends_on:
#      - core
      - tbot_db
    networks:
      - tbot
networks:
  tbot:
    driver: bridge