package com.mawus.core.domain;

public enum Command {
    START,
    REGISTRATION,
    ENTER_NAME,
    ENTER_PHONE_NUMBER,
    ADD_TRIP,
    LIST_TRIPS,
    SELECT_TRANSPORT,
    NEXT_STEP,
    ENTER_CITY_DEPARTUERE, ENTER_CITY_ARRIVAL, ENTER_DEPARTURE_DATE, COMPLETE_TRIP_CREATION, SELECT_TRIP
}
